### ISSUE TITLE
Server goes down after changing the model

### ISSUE THREAD

**Issue by Mosha92blr** [tzole1155/ThreeDit#2]
Hi, nice work with the 360 depth estimation! 

Idk why but your server goes down after the changing the model, it happened earlier yesterday and today as well. 

Also, I’m totally noob at the programming just researching GitHub to find any repositories to solve the task with the creating 3D dollhouse view for our virtual tours. Trying to do that thru the photogrammetry, but getting problems with the alignment of panoramas. Trying to convert 360 images to the point clouds to align PCs instead of aligning 360 panoramas. It would be great if you share any insights if you have time!

Thank you!

**Comment by tzole1155** [comment]
Hello Mosha92blr,
 
Thank you for the kind words about the 360-depth estimation.

Regarding the server going down, it could be due to limited resources provided by the Streamlit platform. Alternatively, try running the app locally on your computer. You would need to download the code from the GitHub repository and set up a local environment to run the app.

As for creating a 3D dollhouse view using photogrammetry, it sounds like you're on the right track with converting 360 images to point clouds. 
However, aligning the point clouds can be a challenging task, which I have not done before.

I hope this helps! 

Let me know if you have any further questions.

Best,

Giorgos

**Comment by Mosha92blr** [comment]
Thank you very much!
